---
# tasks file for jolokia
- name: Create deploy directory
  file:
    path: "{{ deploy_dir }}"
    state: directory
    owner: "{{ user_owner }}"
    group: "{{ user_owner }}"
    recurse: yes

- name: Ensure requests is on latest version
  become: yes
  pip:
    name: requests
    state: latest

- name: Download from maven repository
  include_role:
    name     : install-from-maven
  vars:
    file_url: "{{ jolokia_url }}"

- name: Create link to tomcat7 webapps
  become: yes
  file:
    src: "{{ deploy_dir }}jolokia-war-{{ jolokia_version }}.war"
    dest: /var/lib/tomcat7/webapps/jolokia.war
    state: link
    force: yes

- name: Restart tomcat
  become: yes
  service:
    name: tomcat7
    state: restarted

- name: Copy python jolokia client
  become: yes
  copy:
    src: "files/jolokia.py"
    dest: "/usr/local/bin/pyjolokia"
    owner: "{{ user_owner }}"
    group: "{{ user_owner }}"
    mode: 0544

- name: Ensure pyjokola is installed
  become: yes
  pip:
    name: pyjolokia
    state: latest
